# Copyright (c) Arunkumar Krishnakumar

name: yamllint

on:
  workflow_dispatch:
    inputs:
      Manual_run:
        description: Select for manual run
        type: boolean
        required: false
        default: true



jobs:
  yaml-linter:
    runs-on: ubuntu-latest
    name: yamllint
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        
      - name: Printing Shell
        shell: bash
        run: |
          echo "Running on ${{ runner.os }}"

      - name: yamllint Action
        uses: ./
        shell: bash
