# Copyright (c) Arunkumar Krishnakumar

name: yamllint

on:
  workflow_dispatch:
    inputs:
      Manual_run:
        description: Select for manual run
        type: boolean
        required: false
        default: true



jobs:
  wait_for_approval:
    runs-on: ubuntu-latest
    name: yamllint
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: yamllint Action
        uses: ./
